CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1024)                           NOT NULL,
    is_available BOOLEAN                                 NOT NULL DEFAULT FALSE,
    owner_id     BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_booking TIMESTAMP WITHOUT TIME ZONE          NOT NULL,
    end_booking   TIMESTAMP WITHOUT TIME ZONE          NOT NULL,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR(8)                              NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(1024)                           NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id)
    );